package generator

import (
	"fmt"
	"strings"

	"github.com/fractalx-org/fractalx-cli/internal/model"
)

func genReadme(spec *model.ProjectSpec) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# %s\n\n", spec.ArtifactID))
	if spec.Description != "" {
		b.WriteString(spec.Description + "\n\n")
	}
	b.WriteString("Generated by [FractalX Initializr](https://start.fractalx.dev)\n\n")

	// Services table
	b.WriteString("## Services\n\n")
	b.WriteString("| Service | Port | Database | Entities |\n")
	b.WriteString("|---------|------|----------|----------|\n")
	for _, svc := range spec.Services {
		entities := make([]string, len(svc.Entities))
		for i, e := range svc.Entities {
			entities[i] = e.Name
		}
		entStr := strings.Join(entities, ", ")
		if entStr == "" {
			entStr = "—"
		}
		b.WriteString(fmt.Sprintf("| `%s` | %d | %s | %s |\n", svc.Name, svc.Port, svc.DB, entStr))
	}
	b.WriteString("\n")

	// Infrastructure
	var infraItems []string
	if spec.Infra.Registry {
		infraItems = append(infraItems, "- `fractalx-registry` — service registry (port 8761)")
	}
	if spec.Infra.Gateway {
		infraItems = append(infraItems, "- `fractalx-gateway` — API gateway (port 9999)")
	}
	if spec.Infra.Admin {
		infraItems = append(infraItems, "- `fractalx-admin` — topology dashboard (port 9090)")
	}
	if spec.Infra.Saga {
		infraItems = append(infraItems, "- `fractalx-saga-orchestrator` — distributed saga (port 8099)")
	}
	if spec.Infra.Observability {
		infraItems = append(infraItems, "- Jaeger — distributed tracing (port 16686)")
		infraItems = append(infraItems, "- `logger-service` — log aggregation (port 9099)")
	}

	if len(infraItems) > 0 {
		b.WriteString("## Generated Infrastructure\n\n")
		b.WriteString(strings.Join(infraItems, "\n") + "\n\n")
	}

	// Sagas
	if len(spec.Sagas) > 0 {
		b.WriteString("## Distributed Sagas\n\n")
		for _, saga := range spec.Sagas {
			line := fmt.Sprintf("- **`%s`** — owner: `%s`", saga.SagaID, saga.Owner)
			if saga.Compensation != "" {
				line += fmt.Sprintf(", compensation: `%s`", saga.Compensation)
			}
			b.WriteString(line + "\n")
		}
		b.WriteString("\n")
	}

	// Getting started
	b.WriteString("## Getting Started\n\n")
	if spec.Infra.Docker {
		b.WriteString("```bash\n# Start infrastructure\ndocker compose -f docker-compose.dev.yml up -d\n```\n\n")
	}
	b.WriteString("```bash\n# Run the application\nmvn spring-boot:run -Dspring-boot.run.profiles=dev\n```\n\n")

	b.WriteString("## Decompose to Microservices\n\n")
	b.WriteString("```bash\nmvn fractalx:decompose\n```\n\n")
	b.WriteString("This will analyze your `@DecomposableModule` boundaries and generate fully deployable microservices.\n")

	return b.String()
}
